### PR TITLE
Added tips and tricks

### PR DESCRIPTION
**Pull request by Septiple**
See the PYCP tips commit for details.

### CODE REVIEW

**Comment by notnotmelon** [comment]
The blimp page seems nice.

My impression is that pY heat mechanics are generally incomplete and subject to change. Personally I'm against creating wiki pages for WIP features. @kingarthur91 what's your thoughts on this one?

**Comment by notnotmelon** [comment]
Is it possible to add a thermosolar page? The thermosolar mechanics may not be immediately obvious to players.

**Comment by Septiple** [comment]
Good point, I will add a thermosolar page!

I probably went overboard with the nuclear research description. The main point was that 'nuclear research' doesn't give you good power generation, you need a different tech for that, since I see plenty of questions about it in the Py discord. Will shorten it - I tried to make it less dry than I initially made it, but I probably went too far in the other direction.

**Comment by notnotmelon** [comment]
Thank you. I don't know how much progress you have made, but my idea for an alternative solution is to rename the vanilla reactor to "Breeder reactor". Should convey they same information.

Let me know if you have any questions regarding thermosolar.

**Comment by Septiple** [comment]
Even better! Then I can remove the nuclear research tip entirely. The fewer things need tips, the better.

Will do, thanks for the offer.

**Comment by Septiple** [comment]
I added a tip for thermosolar 1 and 2. I considered adding one for 3 and 4, but they're quite obvious I'd say, so they probably don't need their own tip. Happy to make one though if you'd like.

**Review by notnotmelon — APPROVED** [review]
Merged.

It's possible to use pipes in a thermosolar setup, you just need to pump the cold salt to the hot salt.

**Pull request merged**
